name: product_detail_app
description: A simple product detail page in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add the necessary packages for carousel, icons, and SVG handling

  carousel_slider: ^4.2.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^1.0.3
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
# For internationalization support
flutter:
  uses-material-design: true

  assets:
    - assets/images/

